### ISSUE TITLE
Missing dependency on AnimatedGIFReadWriter

### ISSUE THREAD

**Issue by cdlm** [JurajKubelka/DiscordSt#69] opened 2018-08-20 17:12 UTC
Loading in a fresh Pharo 7 image complains about this class missing

**Comment by JurajKubelka** [comment] 2018-08-21 13:04
Thanks for the report. I think @darth-cheney who changed the animated GIF reader and writer, is working on DiscordSt changes.

**Comment by darth-cheney** [comment] 2018-08-21 13:36
Hey @cdlm 

I'm (slowly, sorry) working on a fix for this. The issue is that the animated GIF implementation has changed between P6.1 and P7. `AnimatedGIFReadWriter` is no longer a thing, and the API for `GIFReadWriter` has changed.
  
Unless you want to use the animated GIF features of DiscordSt, it's safe to just "proceed" when you get that warning.

**Comment by JurajKubelka** [comment] 2018-08-21 13:41
Thank you, @darth-cheney for the information. And please, do no say "sorry", nobody was hurt :-) 

Maybe a quick solution could be that animated gifs are not supported by DiscordSt in Pharo 7? What do you think?

**Comment by darth-cheney** [comment] 2018-08-21 13:47
That can be one option, I suppose.
  
My real problem is not the fix (I already have fixed it on my machine), but preserving a "compatibility layer" between 6.1 and 7. I'm at the horizon of my knowledge when dealing with this question — and it's a design / patterns question for sure.
  
If you wanted to have a separate version of DiscordSt for 7 I could push a fix later this evening and it would work. But I'm not even sure how to do the "check for the version of Pharo" thing when installing...

**Comment by JurajKubelka** [comment] 2018-08-23 17:43
Hi @darth-cheney, one example to deal with different Pharo versions during installation is here: https://github.com/feenkcom/gtoolkit-examples/blob/master/src/BaselineOfGToolkitExamplesEngine.package/BaselineOfGToolkitExamplesEngine.class/instance/baseline..st

```Smalltalk
baseline: spec
	<baseline>
	spec for: #common do: [ 
		spec
			package: 'GToolkit-Examples';
			package: 'GToolkit-Examples-UI' with: [ spec requires: #('GToolkit-Examples') ].			
	].
	spec for: #'pharo6.x' do: [ 
		spec
			package: 'GToolkit-Examples-UI-Nautilus'.			
	]
```

You can define `spec for: #common do:` for all Pharo versions, `spec for: #'pharo6.x' do:` and `spec for: #'pharo7.x' do:` just for a specific Pharo versions.

**Comment by cdlm** [comment] 2018-09-06 11:48
Was this fixed? I don't see the warning anymore…

**Comment by darth-cheney** [comment] 2018-09-06 14:08
Yo I have not gotten around to making any fixes yet. Been looking for work and hustling freelance to pay the rent and it's taking up all of my time at the moment

**Closed as completed** 2020-06-24 13:41 UTC
Labels: wontfix
